### ISSUE TITLE
Doit-on parler de start-up d'innovation sociale?

### ISSUE THREAD

**Issue by jvtrudel** [mouvement-16aout/Maison-democratie-Rimouski#2]
Comment doit-on présenter le projet? En particulier, doit-on utiliser l'argo entreprenarial et la dénomination de *start-up* d'innovation sociale tel que le propose @IkoDulac ?

**Comment by rbourdi** [comment]
START = démarrer, UP = haut, il y a une idée d'explosivité là-dedans que je trouve contradictoire avec l'aspect social. Cela s'inscrit clairement dans le paradigme capitaliste, où la force de la croissance est le meilleur étalon de la réussite d'un projet. Même si, ne nous le cachons pas, nous avons l'ambition de croître.

**Comment by rbourdi** [comment]
Par ailleurs vous dites que ces start-ups feraient des "études de marché". Là aussi les mots ont un sens!

**Comment by jvtrudel** [comment]
Pas certain que ça en vaille la peine à ce stade de s'embarquer sur cette voie. On pourrait s'en tenir à un lieu rassembleur où il est possible de se rencontrer, discuter et faire des choses en tant que citoyens.

**Comment by jvtrudel** [comment]
Par contre, si l'idée est que les idées citoyennes qui y émergent prennent vie, se développent et acquièrent leur indépendance, c'est bien. Mais est-ce qu'on doit absolument avoir cet objectif dès le départ?

**Comment by rbourdi** [comment]
Non. Elles le feront si elles le souhaitent. C'est le "droit des peuples à disposer d'eux-mêmes"!

**Comment by IkoDulac** [comment]
@jvtrudel, la question de départ est mal posée. Bien sûr que nous ne "devons" pas utiliser un argo entrepreneurial. La question pourrait plutôt être : est-ce une erreur d'inviter les entrepreneurs (ou ceux et celles qui y voit un potentiel économique) ?
Est-ce que d'employer cet argo peut rendre la Maison rebutante pour d'autres alliés ?
Est-ce qu'on veut déjà trier certaines possibilités ?

Mon objectif de départ était de donner des exemples facile à imaginer et aussi concrets que possible des possibilités de la Maison.

**Comment by IkoDulac** [comment]
il y a deux questions, non ? Comment présenter le projet (autrement dit, quel titre ?) et Doit-on parler de start-up ?
Pour la deuxième question, je crois que @rbourdi y répond bien : Il ne s'agit pas de définir ce que la Maison va être. J'ajoute que si je le mentionne c'est pour exemplifier, pour permettre d'imaginer les possibilités.
pour la première, je vois que ce serais un titre maladroit qui ne présente pas bien nos intentions et allégeances (même si différentes) du moment.

Il reste donc deux propositions de titre : Maison de la démocration et Centre local de collaboration

**Comment by IkoDulac** [comment]
Personnellement j'opte pour ma proposition : Centre de collaboration.
Je crois que l'acception commune du mot démocratie représente mal l'idéal de collaboration et de délibération que je poursuis.

**Comment by jvtrudel** [comment]
Dans *démocratie* tout comme dans *citoyen*, il y a l'idée d'une démarche politique. Ce qui n'est pas nécessairement le cas avec *collaboration*.
