### ISSUE TITLE
Niveau de frontalité de la critique

### ISSUE THREAD

**Issue by jvtrudel** [mouvement-16aout/Maison-democratie-Rimouski#3]
Le projet de la maison de la démocratie est une critique de la démarche de budget participatif de la ville de Rimouski. Non pas que nous critiquons l'idée d'un budget participatif, mais la mollesse et le peu d'ambition de sa mise en pratique par la ville. 

Aussi, en présentant un projet de lieu de vie de la démocratie, nous souhaitons mettre de l'avant l'idéal de participation citoyenne. Nous optons pour un critique constructive et "non-conflictuelle". 

[Dans une révision de @rbourdi](https://github.com/mouvement-16aout/Maison-democratie-Rimouski/commit/63fada18016ee1081c518e4aacd8e51e47f081f7), celui-ci propose: 
    
  > Nous pensons qu'au lieu de servir à la réalisation de quelques projets ponctuels, ce budget participatif peut avoir de plus grandes ambitions [...]

Or, celui-ci amène l'idée de proposer directement une nouvelle démarche à la ville afin de remplacer le processus actuel. Sans argumenter que cela soit inintéressant, si nous allons dans ce sens, nous risquons de nous disqualifier du processus actuel et/ou de limiter l'adhésion populaire à notre projet.

Sans renier l'objectif de modifier en profondeur pratique de la démocratie municipale à Rimouski, nous pourrions ne pas le présenter explicitement et garder notre critique à un niveau moins frontal. Le projet, sa réalisation et ses retombées étant la critique et son inattaquabilité au niveau de la forme, sa force.

**Comment by rbourdi** [comment]
C'est mon "au lieu" qui est maladroit.

**Comment by rbourdi** [comment]
"Nous pensons qu'au lieu de servir à la réalisation de quelques projets ponctuels, ce budget participatif peut avoir de plus grandes ambitions; qu'en plus de "concrétiser un objectif" de participation citoyenne, il doit être utilisé pour construire la participation citoyenne de demain."

Je propose de changer par: ""Nous pensons qu'au-delà de la réalisation de quelques projets ponctuels, ce budget participatif peut être utilisé pour construire la participation citoyenne de demain."

**Comment by jvtrudel** [comment]
Et pourquoi pas quelque chose du genre:

> Nous proposons un lieu où il soit possible de construire la participation citoyenne à Rimouski

**Comment by rbourdi** [comment]
OK

**Comment by rbourdi** [comment]
J'ai fait le changement mais ça ne s'affiche pas sur le site web.

**Comment by jvtrudel** [comment]
Ça se peu qu'il y ait un petit délai. Ça y est maintenant?
