### ISSUE TITLE
Explicitez l'objectif de la MDR et décrire les types d'activités qui s'y tiendront

### ISSUE THREAD

**Issue by jvtrudel** [mouvement-16aout/Maison-democratie-Rimouski#4]
Un lieu: 
  - axé sur le développement de projet, 
  - de vie, discussion et rassemblement,
  - pour évènement à saveur politique,
  - l'éducation libre
...

**Comment by IkoDulac** [comment]
- l'éducation libre.

**Comment by IkoDulac** [comment]
Développement de projet, c'est pas trop vague ? un projet ça peut être n'importe quoi et tout n'est pas possible dans une MDR. On peut déjà se limiter un minimum. Des projets à caractère collaboratif je disais... ou alors ou ne fait que nommer les exemples qu'on a jusqu'à présent (atelier partagé, cuisine semi commerciale, café communautaire etc.)
Même chose pour évènement à saveur politique... on parle de débats, de conférences, de laboratoire pour un budget participatif de plus grande envergure ?

**Comment by rbourdi** [comment]
J'abonde dans le sens d'Iko. Je crois que jusqu'à présent, on insiste un peu trop sur un côté "incubateur de projets" qui n'est pas notre rôle. On fournit seulement un espace de discussion, de rencontres, de diffusion dans lequel les gens qui veulent développer un projet rencontreront d'autres personnes qui seront peut-être intéressées... Ils pourront utiliser les locaux de la MDR en autant qu'ils laissent de la place aux autres.
Peut-être devrions-nous nous concentrer sur quelques fonctions qui faciliteront ces rencontres/échanges. Cuisine collective, café, salle multi, atelier de réparation, par exemple.

**Comment by rbourdi** [comment]
J'ai modifié le texte, je crois qu'il représente un peu mieux l'idée que nous avions.

**Comment by jvtrudel** [comment]
C'est mon avis aussi. J'avais soulevé la question parce que l'idée d'incubateur et de start-up d'innovation sociale était apparue fortement dans la première ébauche de @IkoDulac .

Tes dernières modifications @rbourdi sont en effet plus proches de nos dernières discussions.
